### ISSUE TITLE
Integration von Gruppen

### ISSUE THREAD

**Issue by ChUrl** [hhu-propra2/abschlussprojekt-big_f_for_auas#101]
Jo Leute, ich wollte mal fragen wie ihr bei euch die Integration von Gruppen handhabt (falls ihr sowas macht), damit wir wissen welche Informationen wir über unsere Api bereitstellen müssen. Wär also schön zu wissen ob ihr zum Beispiel eine Funktion zum allgemeinen Datenabgleich braucht, oder nur speziellere Anfragen nach einzelnen Gruppen (z.B.) stellt. Außerdem wollen wir wissen was für Informationen über Gruppen ihr bei euch verwendet (sowas wie Titel, Teilnehmer oder so).

Wir stimmen unsere Api dann mit den Senioren ab und stellen nur die nötigen Funktionen bereit.

Wenn ihr sowas gar nicht braucht einfach ignorieren :)

**Comment by p-betula-pendula** [comment]
Hi Christoph,

wir werden den Usern ermöglichen, nur bestimmte Gruppen zu einer Umfrage oder Terminabstimmung zuzulassen. Wir brauchen also alle Gruppen mit ihren Mitgliedern und ein paar grundlegenden Metainformationen.

Also den Titel/Name der Gruppen und eventuell zusätzlich eine ID, falls die User die Gruppen anhand der ID referenzieren sollen (ich denke an so etwas wie _termine1_ oder so). Vielleicht auch eine Beschreibung, falls ihr eine habt. Zu jeder Gruppe brauchen wir dann die IDs der zugehörigen Nutzer. Wenn ihr uns dabei direkt noch die Klarnamen der Nutzer übergebt, beschweren wir uns sicher nicht, ansonsten schauen wir die selbst nach.

Ich denke an irgendwas dieser Art:

```
{
    "id": "termine1",
    "name": "Terminfindung und Abstimmung",
    "participants": [
        {
            "id": "orga",
            "first-name": "Александр",
            "last-name": "Schmitt"
        },
        {
            "id": "studentin123",
            "first-name": "Lisa-Luise Hannibal",
            "last-name": "Müller"
        },
        {
            "id": "student456",
            "first-name": "Franz Heinz-Joseph",
            "last-name": "Christkind"
        }
    }
}
```

Aber im Endeffekt richten wir uns da auch einfach nach dem, was ihr uns gebt. Wie läuft das, wenn sich die Gruppen ändern, habt ihr dafür Benachrichtigungen implementiert, die wir empfangen können oder müssen wir die Daten regelmäßig abgleichen?

**Comment by ChUrl** [comment]
Das genaue Format teile ich euch Montag irgendwann mit, nachdem wir das mit der anderen Gruppenbildung abgesprochen haben, ihr kriegt aber aufjedenfall gruppentitel/beschreibung, ne id + mitgliederliste.

Für die Änderungen schicken wir wahrscheinlich eine Nummer mit, welche ihr dann regelmäßig zurückschickt mit entsprechenden Anfragen. Sicher weiß ich das aber auch erst Montag, ich sag dann bescheid

**Comment by ChUrl** [comment]
Ok also wie es aussieht ist es gar nicht nötig, dass beide Gruppenbildung-Gruppen eine einheitliche Schnittstelle bereitstellen. Je nachdem mit welcher Gruppe ihr gearbeitet habt könnt ihr das einfach beibehalten
