### ISSUE TITLE
Spring Security: Daten des Default-Users hardcoden

### ISSUE THREAD

**Issue by p-betula-pendula** [hhu-propra2/abschlussprojekt-big_f_for_auas#22]
Um nicht das ständig wechselnde Passwort des von Spring Security erzeugten Standardnutzers aus der Konsole kopieren zu müssen, sollten die Daten, solange Spring Security noch nicht konfiguriert ist, manuell in der application.properties eingetragen werden.

**Comment by nichennig** [comment]
Oder wir machen direkt die keycloak integration 🤔. Muss ja sowieso gemacht werden, und dafür müssen wir auch nur ein paar Konfigurationen ändern und z. B. mit '@PreAuthorize(passende_rolle)' an dem jeweiligen Controller die Zugangsbeschränkung festlegen

**Comment by p-betula-pendula** [comment]
@nichennig Spring Security mach ich als nächstes
